version: "3.3"

networks:
  network:
    ipam:
      driver: default
      config:
        - subnet: '178.9.0.0/16'

services:

  server:
    build:
      context: ./
      dockerfile: ./dockerfile_server_job
    container_name: geak-server-job
    restart: always
    ports:
      - '18686:8686'
    depends_on:
      - mysql
      - redis
    links:
      - mysql
      - redis
    networks:
      network:
        ipv4_address: 178.9.0.12

  mysql:
    image: mysql:5.6
    container_name: geak-mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci #设置utf8字符集
    restart: always
    ports:
      - "13306:3306"  # host物理直接映射端口为13306
    environment:
      MYSQL_DATABASE: 'geak' # 初始化启动时要创建的数据库的名称
      MYSQL_ROOT_PASSWORD: 'Jcc@744578095' # root管理员用户密码
    networks:
      network:
        ipv4_address: 178.9.0.13

  redis:
    image: redis:6.0.6
    container_name: geak-redis # 容器名
    restart: always
    ports:
      - '16379:6379'
    networks:
      network:
        ipv4_address: 178.9.0.14

