[db]
    addr = "178.9.0.13:3306"
    dbName = "geak"
    userName = "root"
    password = "Jcc@744578095"
    config = "charset=utf8&parseTime=true&loc=Local"
[redis]
    db = 0
    addr = "178.9.0.14:6379"
    password = ""
[app]
    resources = "./resources"
