[db]
    addr = "172.16.33.205:3308"
    dbName = "geak"
    userName = "root"
    password = "root"
    config = "charset=utf8&parseTime=true&loc=Local"
[redis]
    db = 0
    addr = "172.16.33.205:13308"
    password = ""